

CREATE table  IF NOT EXISTS users(
    id int generated by default as identity,
    email varchar(64),
    login varchar (64),
    name varchar (64),
    birthday date
);

INSERT INTO users (email, login,name,birthday)
VALUES ('tom@mail', 'ThomasC','Andersun', '2000-10-10 ');

create table if not exists friendships(
    user_Id INTEGER REFERENCES users(id),
    friend_Id INTEGER REFERENCES users(id)
);